-- DROP TABLE IF EXISTS PEDIDOS_PRODUTOS;
-- DROP TABLE IF EXISTS PRODUTOS;
-- DROP TABLE IF EXISTS PEDIDOS;
-- DROP TABLE IF EXISTS TIPO_PAGAMENTO;
-- DROP TABLE IF EXISTS TIPO_PRODUTO;

CREATE TABLE TIPO_PRODUTO(
    TIPO_PRODUTO_ID SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(60)

);

CREATE TABLE TIPO_PAGAMENTO(
    TIPO_PAGAMENTO_ID SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(60)
);

CREATE TABLE PEDIDOS(
    PEDIDOS_ID SERIAL PRIMARY KEY,
    DATA_COMPRA DATE,
    ID_TIPO_PAGTO INTEGER,
    VALOR_TOTAL  DECIMAL,
    FOREIGN KEY (ID_TIPO_PAGTO) REFERENCES TIPO_PAGAMENTO(TIPO_PAGAMENTO_ID)
);

CREATE TABLE PRODUTOS(
    PRODUTOS_ID SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(60),
    VALOR DECIMAL,
    ID_TIPO_PRODUTO INTEGER,
    FOREIGN KEY (ID_TIPO_PRODUTO) REFERENCES TIPO_PRODUTO (TIPO_PRODUTO_ID)
);


CREATE TABLE PEDIDOS_PRODUTOS(
    PEDIDOS_PRODUTOS_ID SERIAL PRIMARY KEY,
    ID_PEDIDO INTEGER,
    ID_PRODUTO INTEGER,
    QTDE INTEGER,
    VALOR_UNIT DECIMAL,
    VALOR_TOTAL DECIMAL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (PEDIDOS_ID),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (PRODUTOS_ID)
);


INSERT INTO TIPO_PRODUTO (DESCRICAO) VALUES ('CONSUMO'), ('VENDA');

INSERT INTO TIPO_PAGAMENTO (DESCRICAO) VALUES ('A VISTA'),('A PRAZO');

INSERT INTO PEDIDOS (DATA_COMPRA, ID_TIPO_PAGTO, VALOR_TOTAL) VALUES ('2020-07-27','1','16.00'),('2020-08-05', '2', '27.00'),('2020-08-06','1','13.50');

INSERT INTO PRODUTOS (DESCRICAO, VALOR, ID_TIPO_PRODUTO) VALUES 
('SABÃO EM PÓ 2KG', '17.00', '1'),
('COXINHA', '5.00', '2'),
('EMPADINHA', '7.00', '2'),
('BOLO PEDAÇO', '7.50', '2'),
('DETERGENTE 5 LITROS', '8.00', '1'),
('PASTEL', '6.00', '2'),
('PIZZA PEDAÇO', '7.00', '2'),
('SUCO', '7.00', '2');

INSERT INTO PEDIDOS_PRODUTOS (ID_PEDIDO, ID_PRODUTO, QTDE, VALOR_UNIT, VALOR_TOTAL)
VALUES 
('1','2','2','5.00','10.00'),
('1','6','1','6.00','6.00'),
('2','3','3','7.00','21.00'),
('2','6','1','6.00','6.00'),
('3','4','1','7.50','7.50'),
('3','6','1','6.00','6.00');

-- SELECT * FROM TIPO_PAGAMENTO;
-- SELECT * FROM TIPO_PRODUTO;
-- SELECT * FROM PEDIDOS;
-- SELECT * FROM PRODUTOS;
-- SELECT * FROM PEDIDOS_PRODUTOS;

